B3/blog/config/routes.rb
Rails.application.routes.draw do
  namespace :front do
    get"frontend/index" => "frontend#index"
    get"frontend/index/:id" => "frontend#index"
    get"frontend/post/:id" => "frontend#post"
    post"frontend/comment" => "frontend#comment"
    get"frontend/feedback" => "frontend#feedback"
    post"frontend/submitfeedback" => "frontend#submitfeedback"
  end

  namespace :admin do
    get "backend/signup" => "backend#signup"
    get "backend/login" => "backend#login"
    post "backend/register" => "backend#register"
    post "backend/confirm" => "backend#confirm"
    get "backend/index" => "backend#index"
    get "backend/signout" => "backend#signout"
    get "backend/posts" => "backend#posts"
    get "comments/:id" => "comments#index"
    post "comments/pass/:id" => "comments#pass"
    get "feedbacks" => "feedbacks#index"
    resources :comments
    resources :posts


  end

  root "front/frontend#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

B3/blog/app/models/admin.rb
# Schema: Admin(name:string, password_digest:string)
class Admin < ApplicationRecord
  has_secure_password
  validates :name, uniqueness: true
  has_many :posts
end

B3/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

B3/blog/app/models/comment.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end


class Comment < ApplicationRecord
  belongs_to :post
  validates :content, presence: true
  validates :name, presence: true
  validates :email, presence: true, email: true
end

B3/blog/app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :content, presence: true
  validates :nickname, presence: true
end

B3/blog/app/models/post.rb
class Post < ApplicationRecord
  validates :title,  presence: true
  validates :text, presence:true
  belongs_to :admin
  has_many :comments
end

B3/blog/app/controllers/admin/backend_controller.rb
class Admin::BackendController < ApplicationController
  before_action:authorize, :except =>[ :signup, :confirm, :login, :session]

  def signup
  end

  def index
  end

  def register
    if params[:name] == "" || params[:password] == ""
      flash.now[:alert] = "用户名或密码不能为空"
      render "signup"
    elsif Admin.create(:name => params[:name], :password => params[:password]).valid?
      flash[:notice] = "注册成功"

      redirect_to :controller => 'backend' , :action => 'signup'
    else
      flash.now[:alert] = "用户名已存在"
      render "signup"
    end
  end

  def login
  end

  def confirm
    admin = Admin.find_by_name(params[:name])
    password = params[:password]
    if admin && admin.authenticate(password)
      session[:id] = admin.id

      redirect_to :action => 'index'
    else
      flash.now[:alert] = "用户名或密码错误"

      render :action => :login
    end
  end

  def posts
    admin = Admin.find(session[:id])
    @posts =  admin.posts
  end

  def signout
    session[:id] = nil

    redirect_to :action => :signup
  end

end

B3/blog/app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action:authorize

  def index
    @post = Post.find(params[:id])
    @comments1 = @post.comments.where("pass = ?", 0 )
    @comments2 = @post.comments.where("pass = ?", 1 )
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy

    redirect_to  :controller => 'admin/comments', :action => 'index', :id => comment.post
  end

  def pass
    comment = Comment.find(params[:id])
    comment.pass = 1
    comment.save

    redirect_to  :controller => 'admin/comments', :action => 'index', :id => comment.post
  end
end

B3/blog/app/controllers/admin/feedbacks_controller.rb
class Admin::FeedbacksController < ApplicationController
  before_action:authorize

  def index
    @feedbacks = Feedback.all
  end
end

B3/blog/app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action:authorize

  def index
    admin = Admin.find_by_id(session[:id])
    @posts=admin.posts
  end

  def new
    @post = Post.new
  end

  def create
    admin = Admin.find(session[:id])
    @post = admin.posts.build(post_params)
    if @post.save
      redirect_to admin_posts_path
    else
      @tip="标题或正文不能为空"
      render :action => :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_path(@post)
    else
      flash.now[:alert] = "标题或正文不能为空"
      render :action => 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

B3/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authorize
    unless session[:id]
      flash[:notice] = "请先登录"

      redirect_to :controller => "admin/backend", :action => "signup"
    end
  end
end

B3/blog/app/controllers/front/frontend_controller.rb
class Front::FrontendController < ApplicationController
  def index
    @admins = Admin.all
    if params[:id]
      admin = Admin.find(params[:id])
      @posts = admin.posts.page(params[:page]).per(5)
    end
  end

  def post
    @post = Post.find(params[:id])
    @posts = @post.admin.posts
    @comments = @post.comments.where(:pass => 1)
  end

  def comment
    post = Post.find(params[:post])
    if post.comments.create(:content => params[:comment], :pass => 0, :name => params[:name], :email => params[:email]).valid?
      flash[:notice] = "提交成功，正在审核"

      redirect_to :action => 'post', :id => post
    elsif params[:comment] == "" || params[:name] == "" || params[:email] == ""
      flash.now[:alert] = "留言内容、姓名、邮箱不能为空"

      render :post, :locals => { :@post => post, :@posts => post.admin.posts, :@comments => post.comments.where(:pass => 1) }
    else
      flash.now[:alert] = "邮箱格式错误"

      render :post, :locals => { :@post => post, :@posts => post.admin.posts, :@comments => post.comments.where(:pass => 1) }
    end
  end

  def feedback
  end

  def submitfeedback
    if Feedback.create(:content => params[:feedback], :nickname => params[:nickname]).valid?
      flash[:notice] = "提交成功"

      redirect_to :action => 'index'
    else
      flash[:alert] = "反馈内容或昵称不能为空"

      render :feedback
    end
  end
end

B3/blog/app/helpers/admin/backend_helper.rb
module Admin::BackendHelper
end

B3/blog/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

B3/blog/app/helpers/admin/feedbacks_helper.rb
module Admin::FeedbacksHelper
end

B3/blog/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

B3/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

B3/blog/app/helpers/front/frontend_helper.rb
module Front::FrontendHelper
end

B3/blog/app/views/admin/backend/index.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  <%= form_tag("/admin/posts",method: "get") do %>
    <%= submit_tag("文章管理") %>
  <% end %>
  </br>
  <%= form_tag("/admin/backend/posts",method: "get") do %>
    <%= submit_tag("留言管理") %>
  <% end %>
  </br>
  <%= form_tag("/admin/feedbacks",method: "get") do %>
    <%= submit_tag("意见反馈管理") %>
  <% end %>
  </br>
  <%= form_tag("/admin/backend/signout",method: "get") do %>
    <%= submit_tag("退出登录") %>
  <% end %>
  </br>
</div>


</body>
</html>

B3/blog/app/views/admin/backend/login.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  用户登录
  <%= form_tag('/admin/backend/confirm', :method => 'post') do |f| %>
    请输入用户名： <%= text_field_tag(:name) %>
    </br>
    请输入密码： <%= password_field_tag (:password) %>
    </br>
    <%= submit_tag("登录") %>
  <% end %>
</div>


</body>
</html>

B3/blog/app/views/admin/backend/posts.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  <strong>文章标题<strong>
  </br>
  <% @posts.each do |post| %>
  <li>
    <%= link_to post.title, :controller => 'admin/comments', :action => 'index', :id => post %>
  </li>
  <% end %>
  </br>
  </br>
  <%= button_to'返回', { :controller => 'admin/backend', :action => 'index' }, :method => :get %>
</div>


</body>
</html>

B3/blog/app/views/admin/backend/signup.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  用户注册
  <%= form_tag('/admin/backend/register') do |f| %>
    请输入用户名： <%= text_field_tag(:name) %>
    </br>
    请输入密码： <%= password_field_tag (:password) %>
    </br>
    <%= submit_tag("注册") %>
  <% end %>
  </br>
  </br>
  <%= button_to '登录',{ :controller => 'admin/backend', :action => 'login' }, :method => :get %>
  </br>
  <%= button_to '返回主页',{ :controller => 'front/frontend', :action => 'index' }, :method => :get %>
</div>


</body>
</html>

B3/blog/app/views/admin/comments/index.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  <p>未审核留言<p>
  <% @comments1.each do |comment| %>
  <li>
    内容：<%= comment.content %> &nbsp;
    创建日期：  <%= comment.created_at %>
    </br>
    创建人姓名： <%= comment.name %> &nbsp;
    创建人邮箱： <%= comment.email %>
    </br>
    <%= button_to '删除', admin_comment_path(comment), :method => :delete, :data => { :confirm => "Are you sure?" } %>
    </br>
    <%= button_to '通过审核', { :controller => 'admin/comments', :action => 'pass', :id => comment }, :method => :post %>
  </li>
  <% end %>
  </br>
  <p>已审核留言<p>
  <% @comments2.each do |comment| %>
  <li>
    内容：<%= comment.content %> &nbsp;
    创建日期：<%= comment.created_at %>
    </br>
    创建人姓名： <%= comment.name %> &nbsp;
    创建人邮箱： <%= comment.email %> 
    </br>
    <%= button_to '删除', admin_comment_path(comment), :method => :delete, :data => { :confirm => "Are you sure?" } %>
  </li>
  <% end %>
  </br>
  </br>
  <%= button_to'返回', { :controller => 'admin/backend', :action => 'posts' }, :method => :get %>
</div>


</body>
</html>

B3/blog/app/views/admin/feedbacks/index.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  <% @feedbacks.each do |feedback| %>
  <li>
    ID:<%= feedback.id %> &nbsp;
    反馈人昵称：<%= feedback.nickname %>
    </br>
    内容：<%= feedback.content %> &nbsp;
    创建日期：<%= feedback.created_at %>
    </br>
    </br>
  </li>
  <% end %>
  </br>
  </br>
  <%= button_to'返回', { :controller => 'admin/backend', :action => 'index' } , :method => :get %>
</div>


</body>
</html>

B3/blog/app/views/admin/posts/edit.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  <%= form_for @post, :url => admin_post_path(@post), :method => :patch do |f| %>
    <%= f.label :title, "标题" %>
    <%= f.text_field :title %>
    </br>
    <%= f.label :text, "正文" %>
    <%= f.text_area :text %>

    <%= f.submit "更新" %>
<% end %>
</div>


</body>
</html>

B3/blog/app/views/admin/posts/index.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  </ul>
  <% @posts.each do |post| %>
  <li>
    标题：<%= post.title %>
    <%= link_to "显示全文", admin_post_path(post) %>
    <%= link_to '编辑更新', edit_admin_post_path(post) %>
    <%= button_to '删除', admin_post_path(post), :method => :delete, :data => { :confirm => "Are you sure?" } %>
  </li>
  <% end %>
  </ul>

  <%= link_to '新文章', new_admin_post_path %>
  </br>
  </br>
  <%= button_to'返回', { :controller => 'admin/backend', :action => 'index' }, :method => :get %>
</div>


</body>
</html>

B3/blog/app/views/admin/posts/new.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  <% if @post.errors.any? %>
    <%=@tip%>
  <% end %>
  <%= form_for @post, :url => admin_posts_path  do |f| %>
    <%= f.label :title, "标题" %>
    <%= f.text_field :title %>
    </br>
    <%= f.label :text, "正文" %>
    <%= f.text_area :text %>
    </br>
    <%= f.submit "创建" %>
  <% end %>
</div>


</body>
</html>

B3/blog/app/views/admin/posts/show.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title></title>
<style >

</style>
</head>
<body>
<div>
  标题：<%= @post.title %>
  </br>
  正文：<%= simple_format(@post.text) %>

  </br>
  </br>
  <p><%= link_to '返回', :controller => 'admin/posts', :action => 'index' %></p>
</div>


</body>
</html>

B3/blog/app/views/front/frontend/feedback.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title> </title>

  </head>
  <body>
    <%= form_tag("/front/frontend/submitfeedback", method: "post") do %>
      意见反馈: <%= text_area_tag(:feedback) %>
      </br>
      昵称: <%= text_field_tag(:nickname) %>
      </br>
      <%= submit_tag("提交") %>
    <% end %>
    <%= button_to '返回', {:controller => 'front/frontend', :action => 'index'}, :method => 'get' %>
  </body>
</html>

B3/blog/app/views/front/frontend/index.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title> </title>

  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-8">
          <% if @posts %>
            <h2> 文章标题 </h2>
            <% @posts.each do |post| %>
              <%= link_to post.title, :controller => 'front/frontend', :action => 'post', :id => post %>
              </br>
            <% end %>
            <%= paginate @posts %>
          <% end %>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
          <h2> 作者 </h2>
          <% @admins.each do |admin| %>
            <%= link_to admin.name, :controller => 'front/frontend', :action => 'index', :id => admin %>
            </br>
          <% end %>
          </br>
          </br>
          <%= button_to '用户登录', { :controller => 'admin/backend', :action => 'signup' }, :method => :get %>
          </br>
          <%= button_to '意见反馈', { :controller => 'front/frontend', :action => 'feedback'}, :method => :get %>
        </div>
      </div>
    </div>
  </body>
</html>

B3/blog/app/views/front/frontend/post.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title> </title>

  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-8">
          标题：<%= @post.title %>
          </br>
          正文: <%= @post.text %>
          </br>
          </br>
          <% @comments.each do |comment| %>
            留言内容：<%= comment.content %>
            </br>
            创建日期： <%= comment.created_at %>
            </br>
          <% end %>
          <%= form_tag("/front/frontend/comment",method: "post") do %>
            请输入留言内容： <%= text_area_tag(:comment) %>
            </br>
            您的姓名: <%= text_field_tag(:name) %>
            </br>
            您的邮箱：<%= text_field_tag(:email) %>
            <%= hidden_field_tag(:post, @post.id) %>
            </br>
            <%= submit_tag("提交") %>
          <% end %>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
          <h2>文章</h2>
          <% @posts.each do |post| %>
            <%= link_to post.title, :controller => 'front/frontend', :action => 'post', :id => post %>
            </br>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

B3/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="color: green"><%= flash[:notice] %></p>
    <p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>